var query = require('./server.js');

var sql = "SELECT A06_PRODUCT_KPI_TRADE_ORDER_SUM_VIEW.DATEKEY,A06_PRODUCT_KPI_TRADE_ORDER_SUM_VIEW.ORDER_CODE,A06_PRODUCT_KPI_TRADE_ORDER_SUM_VIEW.ORDER_CODE_NAME,sum(A06_PRODUCT_KPI_TRADE_ORDER_SUM_VIEW.ORDER_CNTS),sum(A06_PRODUCT_KPI_TRADE_ORDER_SUM_VIEW.ORIG_AMOUNT),sum(A06_PRODUCT_KPI_TRADE_ORDER_SUM_VIEW.TRADE_AMOUNT) FROM APP.A06_PRODUCT_KPI_TRADE_ORDER_SUM_VIEW as A06_PRODUCT_KPI_TRADE_ORDER_SUM_VIEW group by A06_PRODUCT_KPI_TRADE_ORDER_SUM_VIEW.DATEKEY,A06_PRODUCT_KPI_TRADE_ORDER_SUM_VIEW.ORDER_CODE,A06_PRODUCT_KPI_TRADE_ORDER_SUM_VIEW.ORDER_CODE_NAME";
var sql = "SELECT DIM_DAY.DATEKEY,D05_TRADE_ORDER_CODE.ORDER_CODE_name,count(1) as order_cnts,sum(S06_FFAN_TRADE_ORDER_SUM.ORIG_AMOUNT) as ORIG_AMOUNT ,sum(S06_FFAN_TRADE_ORDER_SUM.TRADE_AMOUNT) as TRADE_AMOUNT FROM DWS.S06_FFAN_TRADE_ORDER_SUM as S06_FFAN_TRADE_ORDER_SUM  LEFT JOIN FFAN.DIM_DAY as DIM_DAY ON S06_FFAN_TRADE_ORDER_SUM.TRANS_DT = DIM_DAY.DATEKEY LEFT JOIN DIM.D05_TRADE_ORDER_CODE as D05_TRADE_ORDER_CODE ON S06_FFAN_TRADE_ORDER_SUM.ORDER_CODE = D05_TRADE_ORDER_CODE.ORDER_CODE group by D05_TRADE_ORDER_CODE.ORDER_CODE_name,DIM_DAY.DATEKEY";
query(sql).then(function(ret){
	console.log(ret);
});

