SELECT A06_PRODUCT_KPI_CATER.DATE_KEY
,D06_APP_CLIENT.CLIENT_NAME
,A06_PRODUCT_KPI_CATER.EVENT_NAME
,sum(A06_PRODUCT_KPI_CATER.PV) as PV
,sum(A06_PRODUCT_KPI_CATER.UV) as UV
FROM APP.A06_PRODUCT_KPI_CATER as A06_PRODUCT_KPI_CATER 
INNER JOIN DIM.D06_APP_CLIENT as D06_APP_CLIENT
ON A06_PRODUCT_KPI_CATER.OS_TYPE = D06_APP_CLIENT.ID

where A06_PRODUCT_KPI_CATER.DATE_KEY >='{{start}}' and A06_PRODUCT_KPI_CATER.DATE_KEY <= '{{end}}' {{filters}}
group by A06_PRODUCT_KPI_CATER.DATE_KEY
,D06_APP_CLIENT.CLIENT_NAME
,A06_PRODUCT_KPI_CATER.EVENT_NAME

order by A06_PRODUCT_KPI_CATER.DATE_KEY desc