SELECT
A06_FFAN_APP_USER_KPI_STAT.DT
,SUM(A06_FFAN_APP_USER_KPI_STAT.NEW_USER_DAY)
,SUM(A06_FFAN_APP_USER_KPI_STAT.HIS_USER)
,SUM(A06_FFAN_APP_USER_KPI_STAT.ACTIVE_USER_DAY)
,SUM(A06_FFAN_APP_USER_KPI_STAT.REMAIN_USER_DAY_RATIO)*100
FROM APP.A06_FFAN_APP_USER_KPI_STAT as A06_FFAN_APP_USER_KPI_STAT 
where A06_FFAN_APP_USER_KPI_STAT.DT>='{{start}}' and A06_FFAN_APP_USER_KPI_STAT.DT<= '{{end}}' {{filters}}
GROUP BY A06_FFAN_APP_USER_KPI_STAT.DT
ORDER BY A06_FFAN_APP_USER_KPI_STAT.DT DESC