SELECT A06_FFAN_SHOPPING_ANALYSIS.DATEKEY,
       D06_APP_CLIENT.CLIENT_NAME,
       SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA1) AS GOODS_GOODSDETAIL_GET_PV,
       SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA2) AS GOODS_GOODSDETAIL_GET_UV, 
       SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA3) AS GOODS_GOODSDETAIL_LEFU_PV,
       SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA4) AS GOODS_GOODSDETAIL_LEFU_UV,
       SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA5) AS GOODS_GOODSDETAIL_LIKE_PV,
       SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA6) AS GOODS_GOODSDETAIL_LIKE_UV 
  FROM APP.A06_FFAN_SHOPPING_ANALYSIS AS A06_FFAN_SHOPPING_ANALYSIS
  LEFT JOIN DIM.D06_APP_CLIENT AS D06_APP_CLIENT
    ON A06_FFAN_SHOPPING_ANALYSIS.OS_TYPE = D06_APP_CLIENT.ID
 WHERE A06_FFAN_SHOPPING_ANALYSIS.REPORT_ID = 1  
and    A06_FFAN_SHOPPING_ANALYSIS.DATEKEY >='{{start}}' and A06_FFAN_SHOPPING_ANALYSIS.DATEKEY <= '{{end}}' {{filters}}
 GROUP BY A06_FFAN_SHOPPING_ANALYSIS.DATEKEY, D06_APP_CLIENT.CLIENT_NAME
HAVING SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA1) > 0 
    OR SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA2) > 0 
    OR SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA3) > 0 
    OR SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA4) > 0 
    OR SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA5) > 0 
    OR SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA6) > 0
 ORDER BY A06_FFAN_SHOPPING_ANALYSIS.DATEKEY DESC