SELECT A06_FFAN_SHOPPING_ANALYSIS.DATEKEY,
       D06_APP_CLIENT.CLIENT_NAME,
       SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA7) AS BRAND_TOPIC_PRODUCT_PV, 
       SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA8) AS BRAND_TOPIC_PRODUCT_UV, 
       SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA9) AS BRAND_TOPIC_BRAND_PV,  
       SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA10) AS BRAND_TOPIC_BRAND_UV,  
       SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA11) AS BRAND_TOPIC_LIKE_PV,  
       SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA12) AS BRAND_TOPIC_LIKE_UV   
  FROM APP.A06_FFAN_SHOPPING_ANALYSIS AS A06_FFAN_SHOPPING_ANALYSIS
LEFT JOIN DIM.D06_APP_CLIENT as D06_APP_CLIENT
ON A06_FFAN_SHOPPING_ANALYSIS.OS_TYPE = D06_APP_CLIENT.ID
 WHERE A06_FFAN_SHOPPING_ANALYSIS.REPORT_ID = 1
and  A06_FFAN_SHOPPING_ANALYSIS.DATEKEY>='{{start}}' and A06_FFAN_SHOPPING_ANALYSIS.DATEKEY<= '{{end}}' {{filters}}
 GROUP BY A06_FFAN_SHOPPING_ANALYSIS.DATEKEY, D06_APP_CLIENT.CLIENT_NAME
HAVING SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA7) > 0 
    OR SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA8) > 0 
    OR SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA9) > 0 
    OR SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA10) > 0 
    OR SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA11) > 0 
    OR SUM(A06_FFAN_SHOPPING_ANALYSIS.DATA12) > 0
 ORDER BY A06_FFAN_SHOPPING_ANALYSIS.DATEKEY DESC