SELECT
A06_PRODUCT_KPI_COMMON_COUPON.DATE_KEY
,D06_APP_CLIENT.CLIENT_NAME
,D06_PLAZA_REGION_INFO.PLAZA_NAME
,sum(A06_PRODUCT_KPI_COMMON_COUPON.RECEIVE_PV) as RECEIVE_PV
,sum(A06_PRODUCT_KPI_COMMON_COUPON.RECEIVE_SUCCESS_PV) as RECEIVE_SUCCESS_PV
,sum(A06_PRODUCT_KPI_COMMON_COUPON.BUY_USERS) as BUY_USERS
,sum(A06_PRODUCT_KPI_COMMON_COUPON.BUY_NUM) as BUY_NUM
,sum(A06_PRODUCT_KPI_COMMON_COUPON.USED_NUM) as USED_NUM
,sum(A06_PRODUCT_KPI_COMMON_COUPON.USED_USERS) as USED_USERS
FROM APP.A06_PRODUCT_KPI_COMMON_COUPON as A06_PRODUCT_KPI_COMMON_COUPON 
INNER JOIN DIM.D06_APP_CLIENT as D06_APP_CLIENT
ON A06_PRODUCT_KPI_COMMON_COUPON.OS_TYPE = D06_APP_CLIENT.ID
INNER JOIN DIM.D06_PLAZA_REGION_INFO as D06_PLAZA_REGION_INFO
ON A06_PRODUCT_KPI_COMMON_COUPON.PLAZA_ID = D06_PLAZA_REGION_INFO.PLAZA_ID
where A06_PRODUCT_KPI_COMMON_COUPON.DATE_KEY>='{{start}}' and A06_PRODUCT_KPI_COMMON_COUPON.DATE_KEY<= '{{end}}' {{filters}}

group by A06_PRODUCT_KPI_COMMON_COUPON.DATE_KEY
,D06_APP_CLIENT.CLIENT_NAME
,D06_PLAZA_REGION_INFO.PLAZA_NAME
order by A06_PRODUCT_KPI_COMMON_COUPON.DATE_KEY   desc