SELECT A06_FFAN_BI_CINEMA_STAT.DATEKEY, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA1) AS HOMEPAGE_NEW_FILM_PV, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA2) AS PLAZA_DETAIL_MOVIE_PV, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA3) AS MOVIE_CITY_INDEX_PV, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA4) AS MOVIE_CINEMA_INDEX_PV, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA5) AS MOVIE_FILM_CURRENT_INDEX_PV, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA6) AS MOVIE_SELECTSEAT_PV, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA7) AS MOVIE_SELECTSEAT_OK_PV, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA8) AS FILM_ORDER_CNTS, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA9) AS FILM_PAY_ORDER_CNTS, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA10) AS PAY_SUCCESS_ORDER_RATE, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA11) AS FILM_PAY_TICKET_CNTS, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA12) AS TRANS_CVR, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA13) AS AVG_DEPTH_OF_ACCESS, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA14) AS REFUND_CNTS, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA15) AS REFUND_RATE, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA16) AS TOTAL_USER_CNTS, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA17) AS TOTAL_TICKET_CNTS, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA18) AS NEW_USER_CNTS, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA19) AS TOTAL_CINEMA_AMOUNT, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA20) AS ONLINE_CINEMA_CNTS, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA21) AS CINEMA_TOTAL_PV, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA22) AS CINEMA_TOTAL_UV 
  FROM APP.A06_FFAN_BI_CINEMA_STAT as A06_FFAN_BI_CINEMA_STAT
 WHERE A06_FFAN_BI_CINEMA_STAT.REPORT_ID = 3
  and  A06_FFAN_BI_CINEMA_STAT.DATEKEY>='{{start}}' and A06_FFAN_BI_CINEMA_STAT.DATEKEY<= '{{end}}'
 GROUP BY A06_FFAN_BI_CINEMA_STAT.DATEKEY          
 ORDER BY A06_FFAN_BI_CINEMA_STAT.DATEKEY DESC