SELECT  CASE
         WHEN A06_FFAN_BI_CINEMA_STAT.DURATION = 7 THEN
          '7days'
         ELSE
          '30days'
       END AS DURATION, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA1) AS NEW_USER_CNTS, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA2) AS CINEMA_PV, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA3) AS CINEMA_UV, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA4) AS AVG_DEPTH_OF_ACCESS, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA5) AS TRANS_CVR, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA6) AS REPEAT_BUY_RATE, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA7) AS REFUND_ORDER_CNTS_RATE, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA8) AS MOVIE_SELECTSEAT_CVR, 
       SUM(A06_FFAN_BI_CINEMA_STAT.DATA9) AS MOVIE_SELECTSEAT_OK_CVR 
  FROM APP.A06_FFAN_BI_CINEMA_STAT as A06_FFAN_BI_CINEMA_STAT
 WHERE A06_FFAN_BI_CINEMA_STAT.REPORT_ID = 1
   AND A06_FFAN_BI_CINEMA_STAT.DATEKEY = '{{start}}'
 GROUP BY A06_FFAN_BI_CINEMA_STAT.DATEKEY,
          CASE
            WHEN A06_FFAN_BI_CINEMA_STAT.DURATION = 7 THEN
          '7days'
         ELSE
          '30days'
          END
 ORDER BY A06_FFAN_BI_CINEMA_STAT.DATEKEY DESC,
          CASE
            WHEN A06_FFAN_BI_CINEMA_STAT.DURATION = 7 THEN
          '7days'
         ELSE
          '30days'
          END