SELECT
A06_PRODUCT_KPI_M_FOODCHANNEL.DATE_KEY
,sum(A06_PRODUCT_KPI_M_FOODCHANNEL.QUEUE_UV)
,sum(A06_PRODUCT_KPI_M_FOODCHANNEL.QUEUE_PV)
,sum(A06_PRODUCT_KPI_M_FOODCHANNEL.FOOD_COPON_PV)
,sum(A06_PRODUCT_KPI_M_FOODCHANNEL.FOOD_COPON_UV)
,sum(A06_PRODUCT_KPI_M_FOODCHANNEL.FOOD_CHANNEL_PV)
,sum(A06_PRODUCT_KPI_M_FOODCHANNEL.FOOD_CHANNEL_UV)
FROM APP.A06_PRODUCT_KPI_M_FOODCHANNEL as A06_PRODUCT_KPI_M_FOODCHANNEL 
where A06_PRODUCT_KPI_M_FOODCHANNEL.DATE_KEY >='{{start}}' and A06_PRODUCT_KPI_M_FOODCHANNEL.DATE_KEY<= '{{end}}' {{filters}}
group by A06_PRODUCT_KPI_M_FOODCHANNEL.DATE_KEY
order by A06_PRODUCT_KPI_M_FOODCHANNEL.DATE_KEY desc