SELECT
A06_PRODUCT_KPI_M_GOODS_FLASH.DATE_KEY
,D06_PLAZA_REGION_INFO.PLAZA_NAME
,sum(A06_PRODUCT_KPI_M_GOODS_FLASH.ORDER_UV)
,sum(A06_PRODUCT_KPI_M_GOODS_FLASH.ORDER_PV)
,sum(A06_PRODUCT_KPI_M_GOODS_FLASH.ORDER_PAY_SUCC_UV)
,sum(A06_PRODUCT_KPI_M_GOODS_FLASH.ORDER_PAY_SUCC_TICKETS)
FROM APP.A06_PRODUCT_KPI_M_GOODS_FLASH as A06_PRODUCT_KPI_M_GOODS_FLASH 
LEFT JOIN DIM.D06_PLAZA_REGION_INFO as D06_PLAZA_REGION_INFO
ON A06_PRODUCT_KPI_M_GOODS_FLASH.PLAZA_ID = D06_PLAZA_REGION_INFO.PLAZA_ID
where A06_PRODUCT_KPI_M_GOODS_FLASH.DATE_KEY >='{{start}}' and A06_PRODUCT_KPI_M_GOODS_FLASH.DATE_KEY<= '{{end}}' {{filters}}
group by A06_PRODUCT_KPI_M_GOODS_FLASH.DATE_KEY,D06_PLAZA_REGION_INFO.PLAZA_NAME
order by A06_PRODUCT_KPI_M_GOODS_FLASH.DATE_KEY desc