SELECT
A06_PRODUCT_KPI_M_GOODS_1.DATE_KEY
,D06_PLAZA_REGION_INFO.PLAZA_NAME
,sum(A06_PRODUCT_KPI_M_GOODS_1.NEW_USER_GOODS)
,sum(A06_PRODUCT_KPI_M_GOODS_1.ORDER_CNTS)
,sum(A06_PRODUCT_KPI_M_GOODS_1.ORDER_PAYSUCC_USERCNTS)
,sum(A06_PRODUCT_KPI_M_GOODS_1.ORDER_PAYSUCC_BUYCNTS)
FROM APP.A06_PRODUCT_KPI_M_GOODS_1 as A06_PRODUCT_KPI_M_GOODS_1
LEFT JOIN DIM.D06_PLAZA_REGION_INFO as D06_PLAZA_REGION_INFO
ON A06_PRODUCT_KPI_M_GOODS_1.PLAZA_ID = D06_PLAZA_REGION_INFO.PLAZA_ID
where A06_PRODUCT_KPI_M_GOODS_1.DATE_KEY >='{{start}}' and A06_PRODUCT_KPI_M_GOODS_1.DATE_KEY<= '{{end}}' {{filters}}
group by A06_PRODUCT_KPI_M_GOODS_1.DATE_KEY,D06_PLAZA_REGION_INFO.PLAZA_NAME
order by A06_PRODUCT_KPI_M_GOODS_1.DATE_KEY desc