SELECT
A06_PRODUCT_KPI_M_OVERALL.DATE_KEY
,sum(A06_PRODUCT_KPI_M_OVERALL.H5_PV)
,sum(A06_PRODUCT_KPI_M_OVERALL.H5_UV)
,sum(A06_PRODUCT_KPI_M_OVERALL.H5_USER_CNTS)
FROM APP.A06_PRODUCT_KPI_M_OVERALL as A06_PRODUCT_KPI_M_OVERALL 
where A06_PRODUCT_KPI_M_OVERALL.DATE_KEY >='{{start}}' and A06_PRODUCT_KPI_M_OVERALL.DATE_KEY<= '{{end}}' {{filters}}
group by A06_PRODUCT_KPI_M_OVERALL.DATE_KEY
order by A06_PRODUCT_KPI_M_OVERALL.DATE_KEY desc