SELECT
A06_PRODUCT_KPI_M_MOVIE.DATE_KEY
,sum(A06_PRODUCT_KPI_M_MOVIE.CHOOSE_TICKET_UV)
,sum(A06_PRODUCT_KPI_M_MOVIE.CHOOSE_TICKET_PV)
,sum(A06_PRODUCT_KPI_M_MOVIE.ORDER_CNTS)
,sum(A06_PRODUCT_KPI_M_MOVIE.ORDER_PAY_SUCC_UV)
,sum(A06_PRODUCT_KPI_M_MOVIE.ORDER_PAY_SUCC_TICKETS)
FROM APP.A06_PRODUCT_KPI_M_MOVIE as A06_PRODUCT_KPI_M_MOVIE 
where A06_PRODUCT_KPI_M_MOVIE.DATE_KEY >='{{start}}' and A06_PRODUCT_KPI_M_MOVIE.DATE_KEY<= '{{end}}' {{filters}}
group by A06_PRODUCT_KPI_M_MOVIE.DATE_KEY
order by A06_PRODUCT_KPI_M_MOVIE.DATE_KEY desc