SELECT
A06_PRODUCT_KPI_MARKETING.DATE_KEY
,D06_APP_CLIENT.CLIENT_NAME
,sum(A06_PRODUCT_KPI_MARKETING.PV) as PV
,sum(A06_PRODUCT_KPI_MARKETING.UV) as UV
,sum(A06_PRODUCT_KPI_MARKETING.BEACON_PV) as BEACON_PV
,sum(A06_PRODUCT_KPI_MARKETING.BEACON_UV) as BEACON_UV
,sum(A06_PRODUCT_KPI_MARKETING.GET_NUM) as GET_NUM
,sum(A06_PRODUCT_KPI_MARKETING.GET_USERS) as GET_USERS
,sum(A06_PRODUCT_KPI_MARKETING.USED_NUM) as USED_NUM
,sum(A06_PRODUCT_KPI_MARKETING.USED_USERS) as USED_USERS
FROM APP.A06_PRODUCT_KPI_MARKETING as A06_PRODUCT_KPI_MARKETING 
INNER JOIN DIM.D06_APP_CLIENT as D06_APP_CLIENT
ON A06_PRODUCT_KPI_MARKETING.OS_TYPE = D06_APP_CLIENT.ID
where A06_PRODUCT_KPI_MARKETING.DATE_KEY >='{{start}}' and A06_PRODUCT_KPI_MARKETING.DATE_KEY <= '{{end}}' {{filters}} 

group by A06_PRODUCT_KPI_MARKETING.DATE_KEY
,A06_PRODUCT_KPI_MARKETING.OS_TYPE
,D06_APP_CLIENT.CLIENT_NAME;