SELECT 
A06_MERCHANT_APP_VERSION_KPI_STAT.DATEKEY        
,A06_MERCHANT_APP_VERSION_KPI_STAT.APP_VERSION    
,SUM(A06_MERCHANT_APP_VERSION_KPI_STAT.ANDROID)   
,SUM(A06_MERCHANT_APP_VERSION_KPI_STAT.IOS)       
FROM APP.A06_MERCHANT_APP_VERSION_KPI_STAT as A06_MERCHANT_APP_VERSION_KPI_STAT  
where A06_MERCHANT_APP_VERSION_KPI_STAT.DATEKEY>='{{start}}' and A06_MERCHANT_APP_VERSION_KPI_STAT.DATEKEY<= '{{end}}' {{filters}}
GROUP BY A06_MERCHANT_APP_VERSION_KPI_STAT.DATEKEY,A06_MERCHANT_APP_VERSION_KPI_STAT.APP_VERSION
ORDER BY A06_MERCHANT_APP_VERSION_KPI_STAT.DATEKEY DESC