SELECT
A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT.DT
,SUM(A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT."OPEN")                 
,SUM(A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT.TRADE)                  
,SUM(A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT.VERIFY)                 
,SUM(A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT.REFUND)                 
,SUM(A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT.MSG)                    
,SUM(A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT.FINA)                   
,SUM(A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT.COUPON)                 
,SUM(A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT.PUB)                    
,SUM(A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT.REGIS)                  
FROM APP.A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT as A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT 
where A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT.DT >='{{start}}' and A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT.DT <= '{{end}}' {{filters}}

GROUP BY A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT.DT
ORDER BY A06_MERCHANT_APP_USER_USE_BUSS_KPI_STAT.DT DESC