SELECT
DIM_DAY.DATEKEY
,D05_TRADE_ORDER_CODE.ORDER_CODE_name
,case when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='PAY_SUCCESS' then '付款成功'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='RETURN_FAIL' then ''
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='TRADE_FINISHED' then '交易完成'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='MER_REVIEW' then '商家审核'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='FAIL' then '退款失败'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='EXCHANGE_SUCCESS' then '兑换成功'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='PROCESSING' then '退款中'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='INITIAL' then '初始状态,未付款'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='TRADE_CANCEL' then '交易取消'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='SUCCESS' then '退款成功'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='TRADE_SUCCESS' then '交易成功'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='REFUND_FINISHED' then '退款终止'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='INIT_ORDER' then '已下单'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='REFUND_CLOSE' then '退款关闭'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='EXCHANGE_TIMEOUT_CLOSE' then '兑换超时关闭'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='PAY_TIMEOUT_ONEPAY' then '交易超时'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='OPER_REVIEW' then '运营审核'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='IN_THE_REFUND' then '退款中'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='APPLICATION' then '申请退款'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='CLOSE' then '订单关闭'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='PAY_TIMEOUT_CLOSE' then '付款超时关闭'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='TRADDE_FINISHED' then '交易已完成' end as ORDER_STATUS
,count(1) as order_cnts
,sum(S06_FFAN_TRADE_ORDER_SUM.ORIG_AMOUNT) as ORIG_AMOUNT
,sum(S06_FFAN_TRADE_ORDER_SUM.TRADE_AMOUNT) as TRADE_AMOUNT
FROM DWS.S06_FFAN_TRADE_ORDER_SUM as S06_FFAN_TRADE_ORDER_SUM 
LEFT JOIN FFAN.DIM_DAY as DIM_DAY
ON S06_FFAN_TRADE_ORDER_SUM.TRANS_DT = DIM_DAY.DATEKEY
LEFT JOIN DIM.D05_TRADE_ORDER_CODE as D05_TRADE_ORDER_CODE
ON S06_FFAN_TRADE_ORDER_SUM.ORDER_CODE = D05_TRADE_ORDER_CODE.ORDER_CODE
where DIM_DAY.DATEKEY >='{{start}}' and DIM_DAY.DATEKEY <= '{{end}}' {{filters}}
group by D05_TRADE_ORDER_CODE.ORDER_CODE_name
,DIM_DAY.DATEKEY,case when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='PAY_SUCCESS' then '付款成功'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='RETURN_FAIL' then ''
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='TRADE_FINISHED' then '交易完成'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='MER_REVIEW' then '商家审核'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='FAIL' then '退款失败'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='EXCHANGE_SUCCESS' then '兑换成功'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='PROCESSING' then '退款中'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='INITIAL' then '初始状态,未付款'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='TRADE_CANCEL' then '交易取消'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='SUCCESS' then '退款成功'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='TRADE_SUCCESS' then '交易成功'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='REFUND_FINISHED' then '退款终止'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='INIT_ORDER' then '已下单'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='REFUND_CLOSE' then '退款关闭'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='EXCHANGE_TIMEOUT_CLOSE' then '兑换超时关闭'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='PAY_TIMEOUT_ONEPAY' then '交易超时'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='OPER_REVIEW' then '运营审核'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='IN_THE_REFUND' then '退款中'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='APPLICATION' then '申请退款'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='CLOSE' then '订单关闭'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='PAY_TIMEOUT_CLOSE' then '付款超时关闭'
when S06_FFAN_TRADE_ORDER_SUM.ORDER_STATUS='TRADDE_FINISHED' then '交易已完成' end
order by DIM_DAY.DATEKEY desc