SELECT
A06_PRODUCT_KPI_FIND_STORE.DATE_KEY
,D06_APP_CLIENT.client_name
,sum(A06_PRODUCT_KPI_FIND_STORE.INDOOR_MAP_PV)
,sum(A06_PRODUCT_KPI_FIND_STORE.INDOOR_MAP_UV)
,sum(A06_PRODUCT_KPI_FIND_STORE.INDOOR_MAP_ROUTE_PV)
,sum(A06_PRODUCT_KPI_FIND_STORE.INDOOR_MAP_ROUTE_UV)
,sum(A06_PRODUCT_KPI_FIND_STORE.INDOOR_MAP_FOOD_PV)
,sum(A06_PRODUCT_KPI_FIND_STORE.INDOOR_MAP_FOOD_UV)
FROM APP.A06_PRODUCT_KPI_FIND_STORE as A06_PRODUCT_KPI_FIND_STORE 
LEFT JOIN DIM.D06_APP_CLIENT as D06_APP_CLIENT
ON A06_PRODUCT_KPI_FIND_STORE.OS_VERSION = D06_APP_CLIENT.ID
where A06_PRODUCT_KPI_FIND_STORE.DATE_KEY >='{{start}}' and A06_PRODUCT_KPI_FIND_STORE.DATE_KEY<= '{{end}}' {{filters}} 
group by A06_PRODUCT_KPI_FIND_STORE.DATE_KEY,D06_APP_CLIENT.client_name 
order by A06_PRODUCT_KPI_FIND_STORE.DATE_KEY desc